# Generated by Django 3.0.3 on 2020-03-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='complete',
            new_name='completed',
        ),
    ]
