# Generated by Django 3.0.3 on 2020-03-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0002_auto_20200311_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
