# Generated by Django 3.0.3 on 2020-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0002_auto_20200314_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
