# Generated by Django 3.0.3 on 2020-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0003_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
