# Generated by Django 3.0.3 on 2020-03-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0004_componenttask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componenttask',
            old_name='belongs_to',
            new_name='project_component',
        ),
        migrations.RenameField(
            model_name='projectcomponent',
            old_name='belongs_to',
            new_name='project',
        ),
    ]
