# Generated by Django 3.0.3 on 2020-03-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0004_auto_20200315_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='date_recorded',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
