# Generated by Django 3.0.3 on 2020-03-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0006_historicalprofile_historicalproject_historicalprojectcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponent',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component', to='assemble.ProjectComponent'),
        ),
    ]
