# Generated by Django 3.0.3 on 2020-03-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0007_auto_20200312_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomponenttest',
            name='task',
        ),
        migrations.RemoveField(
            model_name='projectcomponenttest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projecttest',
            name='user',
        ),
        migrations.AddField(
            model_name='projectcomponent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='assemble.ProjectComponent'),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='ComponentTask',
        ),
        migrations.DeleteModel(
            name='ProjectComponentTest',
        ),
        migrations.DeleteModel(
            name='ProjectTest',
        ),
    ]
