# Generated by Django 3.0.3 on 2020-03-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0009_auto_20200312_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponent',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='assemble.ProjectComponent'),
        ),
    ]
