# Generated by Django 3.0.3 on 2020-03-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0010_auto_20200319_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='assemble.ProjectHistory'),
        ),
    ]
