# Generated by Django 3.0.3 on 2020-03-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0011_auto_20200312_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponent',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
