# Generated by Django 3.0.3 on 2020-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0012_auto_20200313_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponent',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
