# Generated by Django 3.0.3 on 2020-03-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0015_auto_20200323_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectcomponent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprojectcomponent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicalprojectcomponent',
            name='task',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
        migrations.DeleteModel(
            name='HistoricalProjectComponent',
        ),
    ]
