# Generated by Django 3.0.3 on 2020-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0018_projecthistory_previous_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='updated_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
