# Generated by Django 3.0.3 on 2020-04-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0020_projectcomponentindex_projectindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponentindex',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='assemble.ProjectComponentIndex'),
        ),
    ]
