# Generated by Django 3.0.3 on 2020-04-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assemble', '0021_auto_20200405_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomponentindex',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemble.ProjectIndex'),
        ),
    ]
